apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullName" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.api.containerPort }}
