# Install CSI Driver
# kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/secrets-store-csi-driver/main/deploy/secrets-store-csi-driver.yaml

# Define the secrets to be fetched from AWS Secrets Manager
# https://docs.aws.amazon.com/secretsmanager/latest/userguide/ascp-examples.html
# objectName: ARN, Name, or ID of the secret
# objectType: Type of the object, e.g., "secretsmanager", "ssmparameter"
# objectAlias: Alias for the object in the Kubernetes secret
# jmesPath: JMESPath expressions to extract specific fields from the secret

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: default
spec:
  provider: aws
  parameters:
    region: "us-west-2"  # optional, specify the AWS region
    objects: |
      - objectName: "my-secret-name"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db-username"
          - path: "password"
            objectAlias: "db-password"
  secretObjects: # Optional: sync to Kubernetes Secret
    - secretName: synced-k8s-secret
      type: Opaque
      data:
        - objectName: db-username
          key: username
        - objectName: db-password
          key: password
