apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default

---

# Pod using the service account
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  serviceAccountName: my-service-account
  containers:
  - name: my-container
    image: busybox
    command: ["sleep", "3600"]

---

# Service account permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
  # List of API groups:
    # "" (empty string) refers to the core API group (pods, services, endpoints, volumes, configmaps, secrets, serviceaccounts, nodes, bindings)
    # apps:	Apps API group, e.g., Deployments, StatefulSets
    # batch:	Batch API group, e.g., Jobs, CronJobs
    # extensions:	Extensions API group, e.g., Ingresses
    # networking.k8s.io:	Networking API group, e.g., NetworkPolicies
    # rbac.authorization.k8s.io:	RBAC API group, e.g., Roles, RoleBindings
    # and others...
- apiGroups: [""]
  # List of resources:
    # pods:	Pods in the namespace
    # services:	Services in the namespace
    # configmaps:	ConfigMaps in the namespace
    # secrets:	Secrets in the namespace
    # persistentvolumeclaims:	PersistentVolumeClaims in the namespace
    # namespaces:	Namespaces in the cluster
    # and others...
  resources: ["pods"]
  # List of verbs:
    # get:	Read a single resource
    # list:	List resources of that type
    # watch:	Watch for changes
    # create:	Create new resources
    # update:	Modify existing resources
    # patch:	Apply partial updates
    # delete:	Delete a resource
    # deletecollection:	Delete a group of resources
    # impersonate:	Act as another user, group, or service account
    # use:	Grant access to secrets, service accounts, etc.
    # bind:	Allow role bindings to specific roles
    # escalate:	Allow assigning roles with higher privileges
    # *:	Wildcard (all verbs)
  verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: my-service-account
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
